#!/usr/bin/env bash
set -e # halt script on error
##
# Color stuff
##
NORMAL=$(tput sgr0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2; tput bold)
YELLOW=$(tput setaf 3)
SITE_DIR='_site/'


function red() {
    echo "$RED$*$NORMAL"
}

function green() {
    echo "$GREEN$*$NORMAL"
}

function yellow() {
    echo "$YELLOW$*$NORMAL"
}
red '--> Npm stuff..'
npm install
npm install -g bower
bower install
green '--> Jekyll Build.'
gulp build --prod

#bundle exec htmlproof ./_site
